apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-cloud.fullname" . }}
  labels:
    {{- include "go-cloud.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      {{- include "go-cloud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "go-cloud.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image }}:{{ .Values.app.tag }}"
          imagePullPolicy: {{ .Values.app.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.port }}
          env:
            - name: DATABASE_URL
              value: {{ .Values.app.env.databaseUrl | quote }}
            - name: REDIS_URL
              value: {{ .Values.app.env.redisUrl | quote }}
            - name: CACHE_TTL
              value: {{ .Values.app.env.cacheTtl | quote }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.app.probes.readiness.path }}
              port: {{ .Values.app.port }}
            initialDelaySeconds: {{ .Values.app.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.app.probes.liveness.path }}
              port: {{ .Values.app.port }}
            initialDelaySeconds: {{ .Values.app.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.probes.liveness.periodSeconds }}
