apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-cloud.fullname" . }}
  labels:
    {{- include "go-cloud.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      {{- include "go-cloud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "go-cloud.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.app.image }}:{{ .Values.app.tag }}"
          imagePullPolicy: {{ .Values.app.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.port }}
          env:
            - name: DATABASE_URL
              value: postgres://postgres:{{ .Values.postgresql.auth.postgresPassword }}@{{ .Release.Name }}-postgresql:5432/{{ .Values.postgresql.auth.database }}?sslmode=disable
            - name: REDIS_URL
              value: redis://{{ .Release.Name }}-redis:6379/0
            - name: CACHE_TTL
              value: {{ .Values.app.cacheTtl }}
          resources:
            {{- toYaml .Values.app.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.app.probes.readiness.path }}
              port: {{ .Values.app.port }}
            initialDelaySeconds: {{ .Values.app.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.probes.readiness.periodSeconds }}
          livenessProbe:
            httpGet:
              path: {{ .Values.app.probes.liveness.path }}
              port: {{ .Values.app.port }}
            initialDelaySeconds: {{ .Values.app.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.probes.liveness.periodSeconds }}
