{{- if .Values.monitoring.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  labels:
    grafana_datasource: "1"
    {{- include "go-cloud.labels" . | nindent 4 }}
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:{{ .Values.monitoring.prometheus.port }}
        isDefault: true
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:{{ .Values.monitoring.loki.port }}
{{- end }}
