{{- if .Values.monitoring.grafana.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    {{- include "go-cloud.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: {{ .Values.monitoring.grafana.image }}
          ports:
            - containerPort: {{ .Values.monitoring.grafana.port }}
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.monitoring.grafana.adminPassword }}
          volumeMounts:
            - name: datasource
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
            - name: dashboards
              mountPath: /etc/grafana/provisioning/dashboards
              readOnly: true
          resources:
            {{- toYaml .Values.monitoring.grafana.resources | nindent 12 }}
      volumes:
        - name: datasource
          configMap:
            name: grafana-datasource
        - name: dashboards
          configMap:
            name: grafana-dashboard
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    {{- include "go-cloud.labels" . | nindent 4 }}
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: {{ .Values.monitoring.grafana.port }}
      targetPort: {{ .Values.monitoring.grafana.port }}
  type: {{ .Values.monitoring.grafana.serviceType }}
{{- end }}
