{{- if .Values.monitoring.loki.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: loki
  labels:
    {{- include "go-cloud.labels" . | nindent 4 }}
spec:
  selector:
    app: loki
  ports:
    - protocol: TCP
      port: {{ .Values.monitoring.loki.port }}
      targetPort: {{ .Values.monitoring.loki.port }}
{{- end }}
