{{- if .Values.monitoring.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    {{- include "go-cloud.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.monitoring.prometheus.scrapeInterval }}
    scrape_configs:
      - job_name: 'go-cloud'
        static_configs:
          - targets: ['{{ include "go-cloud.fullname" . }}-svc:80']
        metrics_path: /metrics
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:{{ .Values.monitoring.prometheus.port }}']
{{- end }}
