{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    {{- include "go-cloud.labels" . | nindent 4 }}
data:
  password: {{ .Values.postgres.password | b64enc }}
{{- end }}
