apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-cloud.fullname" . }}-svc
  labels:
    {{- include "go-cloud.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "go-cloud.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.app.port }}
